export const ADD_WEBRADIO = 'ADD_WEBRADIO';
export const DELETE_WEBRADIO = 'DELETE_WEBRADIO';
export const EDIT_WEBRADIO = 'EDIT_WEBRADIO';
export const REORDER_WEBRADIO = 'REORDER_WEBRADIO';
export const PLAY_WEBRADIO = 'PLAY_WEBRADIO';
export const STOP_WEBRADIO = 'STOP_WEBRADIO';
