export const ADD_WEBRADIO = 'ADD_WEBRADIO';
export const DELETE_WEBRADIO = 'DELETE_WEBRADIO';
export const EDIT_WEBRADIO = 'EDIT_WEBRADIO';
export const REORDER_WEBRADIO = 'REORDER_WEBRADIO';
export const PLAY_WEBRADIO = 'PLAY_WEBRADIO';
export const STOP_WEBRADIO = 'STOP_WEBRADIO';

export const ADD_FMPRESET = 'ADD_FMPRESET';
export const DELETE_FMPRESET = 'DELETE_FMPRESET';
export const EDIT_FMPRESET = 'EDIT_FMPRESET';
export const REORDER_FMPRESET = 'REORDER_FMPRESET';
export const PLAY_FMPRESET = 'PLAY_WEBFMPRESET';
export const STOP_FMPRESET = 'STOP_FMPRESET';
