#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

start() {
	echo "starting netradio"
	/www/netradio/scripts/netradio.sh &>/var/log/netradio &        
}  

stop() {
	echo "stopping netradio"
	killall netradio.sh madplay
}
