module.exports = {
  debug: 1,
  port: 3000,
  contentDir: 'media',
  contentDirMpd: '',
  serialPort: '/dev/ttyS1',
  serialPortBaudRate: 115200,
  serialPortDelimiter: '\n',
  couchDbName: 'webradio',
  couchDbUrl: 'http://localhost:5984',
  mpdPort: 6600,
  mpdHost: 'localhost',
  alarmOnScriptPath: '/home/webradio/backend/console/alarm.js 1',
  alarmOffScriptPath: '/home/webradio/backend/console/alarm.js 0',
  socketHeartBeatTimeout: 30000,
  socketHeartBeatInterval: 30000,
  mqttHost: '192.168.31.100',
  mqttPort: 1883,
  mqttUsername: '',
  mqttPassword: '',
  airplayMetadataReaderHost: '226.0.0.1',
  airplayMetadataReaderPort: 5555,
};
