export const DEFAULT_MODE = 0;

export const GET_MODE = 'GET_MODE';
export const TOGGLE_POWER = 'TOGGLE_POWER';
export const TOGGLE_SLEEP_TIMER = 'TOGGLE_SLEEP_TIMER';
export const SET_VOLUME = 'SET_VOLUME';
export const TOGGLE_VOLUME_MUTE = 'TOGGLE_VOLUME_MUTE';

export const ADD_WEBRADIO = 'ADD_WEBRADIO';
export const DELETE_WEBRADIO = 'DELETE_WEBRADIO';
export const EDIT_WEBRADIO = 'EDIT_WEBRADIO';
export const SORT_WEBRADIO = 'SORT_WEBRADIO';
export const SELECT_WEBRADIO = 'SELECT_WEBRADIO';

export const ADD_FM_RADIO = 'ADD_FM_RADIO';
export const DELETE_FM_RADIO = 'DELETE_FM_RADIO';
export const EDIT_FM_RADIO = 'EDIT_FM_RADIO';
export const SORT_FM_RADIO = 'SORT_FM_RADIO';
export const SELECT_FM_RADIO = 'SELECT_FM_RADIO';

export const ADD_DAB_RADIO = 'ADD_DAB_RADIO';
export const DELETE_DAB_RADIO = 'DELETE_DAB_RADIO';
export const EDIT_DAB_RADIO = 'EDIT_DAB_RADIO';
export const SORT_DAB_RADIO = 'SORT_DAB_RADIO';
export const SELECT_DAB_RADIO = 'SELECT_DAB_RADIO';
export const RESCAN_DAB_PRESETS = 'RESCAN_DAB_PRESETS';
export const CANCEL_RESCAN_DAB_PRESETS = 'CANCEL_RESCAN_DAB_PRESETS';

export const SELECT_AUDIO_TAB = 'SELECT_AUDIO_TAB';
export const ADD_AUDIO_PLAYLIST = 'ADD_AUDIO_PLAYLIST';
export const DELETE_AUDIO_PLAYLIST = 'DELETE_AUDIO_PLAYLIST';
export const EDIT_AUDIO_PLAYLIST = 'EDIT_AUDIO_PLAYLIST';
export const SORT_AUDIO_PLAYLIST = 'SORT_AUDIO_PLAYLISTO';
export const SELECT_AUDIO_PLAYLIST = 'SELECT_AUDIO_PLAYLIST';
export const SELECT_AUDIO_FOLDER = 'SELECT_AUDIO_FOLDER';
export const RESCAN_AUDIO_FOLDERS = 'RESCAN_AUDIO_FOLDERS';
export const CANCEL_RESCAN_AUDIO_FOLDERS = 'CANCEL_RESCAN_AUDIO_FOLDERS';

export const ADD_AUDIO_FOLDER_TO_PLAYLIST = 'ADD_AUDIO_FOLDER_TO_PLAYLIST';
export const ADD_AUDIO_TRACK_TO_PLAYLIST = 'ADD_AUDIO_TRACK_TO_PLAYLIST';
export const DELETE_AUDIO_FOLDER = 'DELETE_AUDIO_FOLDER';
export const DELETE_AUDIO_TRACK = 'DELETE_AUDIO_TRACK';
export const PLAY_AUDIO_FOLDER = 'PLAY_AUDIO_FOLDER';
export const PLAY_AUDIO_TRACK = 'PLAY_AUDIO_TRACK';
export const TOGGLE_AUDIO_PLAYER_SHUFFLE = 'TOGGLE_AUDIO_PLAYER_SHUFFLE';
export const TOGGLE_AUDIO_PLAYER_PLAY = 'TOGGLE_AUDIO_PLAYER_PLAY';
export const PLAY_PREVIOUS_AUDIO_TRACK = 'PLAY_PREVIOUS_AUDIO_TRACK';
export const PLAY_NEXT_AUDIO_TRACK = 'PLAY_NEXT_AUDIO_TRACK';

export const LOAD_AUDIO_PLAYLIST_TRACK = 'LOAD_AUDIO_PLAYLIST_TRACK';
export const PLAY_AUDIO_PLAYLIST_TRACK = 'PLAY_AUDIO_PLAYLIST_TRACK';
export const STOP_AUDIO_PLAYLIST_TRACK = 'STOP_AUDIO_PLAYLIST_TRACK';

export const SET_SLEEP_TIMER = 'SET_SLEEP_TIMER';
export const SET_ALARM = 'SET_ALARM';
